
version: 2

sources:
  - name: marker
    description: This is a sample B2B SaaS DB
    schema: marker
    tables:
      - name: users
      - name: events
      - name: teams
      - name: tickets
      - name: nps_responses