name: Test dbt-action workflow

on:
  workflow_dispatch:
  push:
    paths:
      - "models/**"

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dbt-action
        id: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          # dbt_command: "dbt run --profiles-dir ."
          dbt_command: "dbt --version"
        # env:
        #   DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
