name: Test dbt-action workflow

on:
  workflow_dispatch:
  push:
    paths:
      - "models/**"

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dbt-run
        id: dbt-run
        uses: ./
        with:
          dbt_command: "dbt --version"

      - name: Get the result
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
